import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  users: defineTable({
    authSubject: v.string(),
    authIssuer: v.string(),
    tokenIdentifier: v.string(),
    email: v.optional(v.string()),
    displayName: v.string(),
    avatarUrl: v.optional(v.string()),
    preferences: v.record(v.string(), v.any()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_tokenIdentifier", ["tokenIdentifier"])
    .index("by_authSubject", ["authSubject"]),
  couples: defineTable({
    name: v.string(),
    inviteCode: v.union(v.string(), v.null()),
    anniversary: v.union(v.string(), v.null()),
    createdBy: v.id("users"),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_inviteCode", ["inviteCode"])
    .index("by_createdBy", ["createdBy"]),
  memberships: defineTable({
    userId: v.id("users"),
    coupleId: v.id("couples"),
    role: v.union(v.literal("creator"), v.literal("partner")),
    status: v.union(v.literal("active"), v.literal("left")),
    joinedAt: v.number(),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_userId", ["userId"])
    .index("by_coupleId", ["coupleId"])
    .index("by_userId_coupleId", ["userId", "coupleId"]),
  events: defineTable({
    coupleId: v.id("couples"),
    createdBy: v.id("users"),
    title: v.string(),
    description: v.union(v.string(), v.null()),
    startsAt: v.number(),
    endsAt: v.union(v.number(), v.null()),
    category: v.union(v.string(), v.null()),
    location: v.union(v.string(), v.null()),
    priority: v.number(),
    isPrivate: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_coupleId", ["coupleId"]),
  plans: defineTable({
    coupleId: v.id("couples"),
    createdBy: v.id("users"),
    title: v.string(),
    description: v.union(v.string(), v.null()),
    category: v.union(v.string(), v.null()),
    targetDate: v.union(v.string(), v.null()),
    budget: v.union(v.number(), v.null()),
    status: v.string(),
    notes: v.union(v.string(), v.null()),
    coverImageUrl: v.optional(v.union(v.string(), v.null())),
    priority: v.number(),
    isPrivate: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_coupleId", ["coupleId"]),
  rituals: defineTable({
    coupleId: v.id("couples"),
    createdBy: v.id("users"),
    title: v.string(),
    description: v.union(v.string(), v.null()),
    cadence: v.string(),
    dueDate: v.union(v.string(), v.null()),
    nextOccurrenceAt: v.union(v.number(), v.null()),
    lastCompletedAt: v.union(v.number(), v.null()),
    streak: v.number(),
    priority: v.number(),
    isPrivate: v.boolean(),
    isActive: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_coupleId", ["coupleId"]),
  checkIns: defineTable({
    coupleId: v.id("couples"),
    authorId: v.id("users"),
    mood: v.union(v.string(), v.null()),
    note: v.union(v.string(), v.null()),
    checkInDate: v.string(),
    isPrivate: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_coupleId", ["coupleId"])
    .index("by_coupleId_and_authorId_and_checkInDate", [
      "coupleId",
      "authorId",
      "checkInDate",
    ]),
  reminders: defineTable({
    coupleId: v.id("couples"),
    createdBy: v.id("users"),
    assignedTo: v.union(v.id("users"), v.null()),
    title: v.string(),
    description: v.union(v.string(), v.null()),
    dueAt: v.number(),
    recurrence: v.union(v.string(), v.null()),
    isCompleted: v.boolean(),
    completedAt: v.union(v.number(), v.null()),
    completedBy: v.union(v.id("users"), v.null()),
    priority: v.number(),
    category: v.union(v.string(), v.null()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_coupleId", ["coupleId"]),
  taskLists: defineTable({
    coupleId: v.id("couples"),
    name: v.string(),
    icon: v.string(),
    color: v.string(),
    sortOrder: v.number(),
    createdBy: v.id("users"),
    createdAt: v.number(),
  }).index("by_coupleId", ["coupleId"]),
  tasks: defineTable({
    listId: v.id("taskLists"),
    coupleId: v.id("couples"),
    title: v.string(),
    notes: v.union(v.string(), v.null()),
    isCompleted: v.boolean(),
    completedAt: v.union(v.number(), v.null()),
    completedBy: v.union(v.id("users"), v.null()),
    assignedTo: v.union(v.id("users"), v.null()),
    dueDate: v.union(v.string(), v.null()),
    priority: v.number(),
    sortOrder: v.number(),
    createdBy: v.id("users"),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_coupleId", ["coupleId"])
    .index("by_listId", ["listId"]),
  journalEntries: defineTable({
    coupleId: v.id("couples"),
    authorId: v.id("users"),
    title: v.union(v.string(), v.null()),
    body: v.string(),
    mood: v.union(v.string(), v.null()),
    isPrivate: v.boolean(),
    mediaUrls: v.array(v.string()),
    mediaStorageIds: v.optional(v.array(v.string())),
    tags: v.array(v.string()),
    entryDate: v.string(),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_coupleId", ["coupleId"])
    .index("by_authorId", ["authorId"]),
  dailyVerseCache: defineTable({
    dateKey: v.string(),
    text: v.string(),
    reference: v.string(),
    translation: v.string(),
    source: v.union(v.literal("remote"), v.literal("fallback")),
    fetchedAt: v.number(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_dateKey", ["dateKey"]),
  loveNotes: defineTable({
    coupleId: v.id("couples"),
    authorId: v.id("users"),
    body: v.string(),
    isPrivate: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_coupleId", ["coupleId"]),
  wishlists: defineTable({
    coupleId: v.id("couples"),
    name: v.string(),
    createdBy: v.id("users"),
    createdAt: v.number(),
  }).index("by_coupleId", ["coupleId"]),
  wishlistItems: defineTable({
    wishlistId: v.id("wishlists"),
    coupleId: v.id("couples"),
    title: v.string(),
    description: v.union(v.string(), v.null()),
    url: v.union(v.string(), v.null()),
    price: v.union(v.number(), v.null()),
    isPurchased: v.boolean(),
    purchasedBy: v.union(v.id("users"), v.null()),
    priority: v.number(),
    sortOrder: v.number(),
    addedBy: v.id("users"),
    createdAt: v.number(),
  })
    .index("by_coupleId", ["coupleId"])
    .index("by_wishlistId", ["wishlistId"]),
  expenses: defineTable({
    coupleId: v.id("couples"),
    title: v.string(),
    amount: v.number(),
    paidBy: v.id("users"),
    currency: v.optional(v.string()),
    splitType: v.string(),
    splitAmount: v.union(v.number(), v.null()),
    category: v.string(),
    date: v.string(),
    isSettled: v.boolean(),
    createdAt: v.number(),
  }).index("by_coupleId", ["coupleId"]),
  milestones: defineTable({
    coupleId: v.id("couples"),
    title: v.string(),
    date: v.string(),
    description: v.union(v.string(), v.null()),
    icon: v.string(),
    createdBy: v.id("users"),
    createdAt: v.number(),
  }).index("by_coupleId", ["coupleId"]),
});
